# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Lathrop
tagline:          'Your tagline'
description:      A professor at the University of Iowa with a bright future ahead of him in mass communication.
url:              http://lathropd.github.io
baseurl:          /profile-hyde/
shortbaseurl:     /profile-hyde
colorscheme:      ''
#options '' (black), theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)


author:
  name:           'Daniel Lathrop'
  url:            ''
  
paginate:         5

# Custom vars
version:          0.8.1

